services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "${MONGO_INITDB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-mydb}
    volumes:
      - mongodb-data:/data/db
    networks:
      - database
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-secret}
    volumes:
      - storage:/data
    networks:
      - storage
    restart: unless-stopped
    command: server /data --console-address ":9001"

networks:
  database:
  storage:

volumes:
  mongodb-data:
  storage:
