services:
  svelte:
    build:
      context: .
      dockerfile: dockerfile
    container_name: svelte
    ports:
      - "5173:5173"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  mongo-data:
